### ISSUE TITLE
Fairness

### ISSUE THREAD

**Issue by asm582** [DIR-LAB/deep-batch-scheduler#10]
Hello, can someone help me reproducing the fairness comparison shared in the paper?
@daidong 

Thanks

**Comment by daidong** [comment]
Hi, @asm582 sure. we will publish that portion of code soon.

**Comment by asm582** [comment]
@daidong  great thank you, eagerly waiting for code or design that you can share with us.

**Comment by zhangdistephen** [comment]
Hi, @asm582. We put the code associated with fairness in these files: HPCEnvFair.py, rl-fair.py, compare-fair.py which are the counterparts of HPCSimPickJobs.py, ppo-pick-jobs.py, compare-pick-jobs.py. You can train, monitor and test similarly.

**Comment by asm582** [comment]
@zhangdistephen  Thank you!!
